---
- name: Build Autoware Universe Dependencies
  hosts: localhost
  connection: local
  vars:
    rosdep_install_dependency_types:
      - buildtool
      - buildtool_export
      - build_export
      - build

  tasks:
    - name: Load collection vars
      ansible.builtin.include_role:
        name: bounverif.ros.collection_vars

    - name: Install CUDA Toolkit
      ansible.builtin.include_role:
        name: bounverif.ros.cuda_toolkit_install

    - name: Install ROS2
      ansible.builtin.include_role:
        name: bounverif.ros.ros2_install

    - name: Install specific distro dependencies
      ansible.builtin.include_role:
        name: bounverif.autoware_universe.distro_setup

    - name: Install external repositories
      ansible.builtin.include_role:
        name: bounverif.ros.repositories

    - name: Install rosdep dependencies
      ansible.builtin.include_role:
        name: bounverif.ros.rosdep_install
