# General Vars
ros_workspace: /tmp/autoware
ros_source_dir:  "{{ ros_workspace }}/src"
ros_build_dir: "{{ ros_workspace }}/build"
ros_install_dir: "/opt/autoware/{{ ros_distro }}/control/"

# Requirement role vars
ros_distro: humble
ros_distro_type: base
collection_name: autoware_control
ros_rmw_implementation: rmw_cyclonedds_cpp

colcon_build_packages_up_to: 
  - "pure_pursuit"

repositories:
  - url: https://github.com/autowarefoundation/autoware.universe.git
    dest: universe
    version: main
  - url: https://github.com/autowarefoundation/autoware_msgs.git
    dest: core/autoware_msgs
    version: main
  - url: https://github.com/autowarefoundation/autoware_common.git
    dest: core/autoware_common
    version: main
  - url: https://github.com/autowarefoundation/autoware_adapi_msgs.git
    dest: core/autoware_adapi_msgs
    version: main
  - url: https://github.com/tier4/autoware_auto_msgs.git
    dest: universe/external/autoware_auto_msgs
    version: tier4/main
  - url: https://github.com/tier4/tier4_autoware_msgs.git
    dest: universe/external/tier4_autoware_msgs
    version: tier4/universe
